### ISSUE TITLE
remove TinyModel dependency from models

### ISSUE THREAD

**Issue by galarant** [buzzfeed/pyfacebook#36]
The [models](https://github.com/buzzfeed/pyfacebook/blob/master/pyfacebook/models.py) for this project are currently defined as TinyModel classes.

Please remove the dependency on TinyModel, and refactor the models as Python base classes instead. We still need to retain the datatypes for the model attributes as they are currently defined (including any inheritance / composition relationships). We should just implement our own custom attribute management instead of relying on TinyModel's attribute management functionality.

This should be pretty straightforward since most (but not ALL) Facebook objects follow the JSON standard, so you can just use the json lib for most of the translation.

Read through the model definitions carefully to identify edge cases. There are too many models to refactor them all at once, so for this ticket just do:

AdAccount
AdCampaign
AdCreative
AdGroup

**Comment by finn** [comment]
This project is no longer being maintained and is now archived.
